// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForceUpdateInfo.proto

package org.nofs.net.proto;

import org.nofs.org.nofs;

public final class ForceUpdateInfoOuterClass {
  private ForceUpdateInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ForceUpdateInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ForceUpdateInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string force_update_url = 1;</code>
     * @return The forceUpdateUrl.
     */
    String getForceUpdateUrl();
    /**
     * <code>string force_update_url = 1;</code>
     * @return The bytes for forceUpdateUrl.
     */
    com.google.protobuf.ByteString
        getForceUpdateUrlBytes();
  }
  /**
   * Protobuf type {@code ForceUpdateInfo}
   */
  public static final class ForceUpdateInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ForceUpdateInfo)
      ForceUpdateInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ForceUpdateInfo.newBuilder() to construct.
    private ForceUpdateInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ForceUpdateInfo() {
      forceUpdateUrl_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ForceUpdateInfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.nofs.ForceUpdateInfoOuterClass.internal_static_ForceUpdateInfo_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.nofs.ForceUpdateInfoOuterClass.internal_static_ForceUpdateInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo.class, org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo.Builder.class);
    }

    public static final int FORCE_UPDATE_URL_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object forceUpdateUrl_ = "";
    /**
     * <code>string force_update_url = 1;</code>
     * @return The forceUpdateUrl.
     */
    @Override
    public String getForceUpdateUrl() {
      Object ref = forceUpdateUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        forceUpdateUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string force_update_url = 1;</code>
     * @return The bytes for forceUpdateUrl.
     */
    @Override
    public com.google.protobuf.ByteString
        getForceUpdateUrlBytes() {
      Object ref = forceUpdateUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        forceUpdateUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(forceUpdateUrl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, forceUpdateUrl_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(forceUpdateUrl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, forceUpdateUrl_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo)) {
        return super.equals(obj);
      }
      org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo other = (org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo) obj;

      if (!getForceUpdateUrl()
          .equals(other.getForceUpdateUrl())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FORCE_UPDATE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getForceUpdateUrl().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ForceUpdateInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ForceUpdateInfo)
        org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.nofs.ForceUpdateInfoOuterClass.internal_static_ForceUpdateInfo_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.nofs.ForceUpdateInfoOuterClass.internal_static_ForceUpdateInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo.class, org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo.Builder.class);
      }

      // Construct using org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        forceUpdateUrl_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.nofs.ForceUpdateInfoOuterClass.internal_static_ForceUpdateInfo_descriptor;
      }

      @Override
      public org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo getDefaultInstanceForType() {
        return org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo.getDefaultInstance();
      }

      @Override
      public org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo build() {
        org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo buildPartial() {
        org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo result = new org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.forceUpdateUrl_ = forceUpdateUrl_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo) {
          return mergeFrom((org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo other) {
        if (other == org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo.getDefaultInstance()) return this;
        if (!other.getForceUpdateUrl().isEmpty()) {
          forceUpdateUrl_ = other.forceUpdateUrl_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                forceUpdateUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object forceUpdateUrl_ = "";
      /**
       * <code>string force_update_url = 1;</code>
       * @return The forceUpdateUrl.
       */
      public String getForceUpdateUrl() {
        Object ref = forceUpdateUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          forceUpdateUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string force_update_url = 1;</code>
       * @return The bytes for forceUpdateUrl.
       */
      public com.google.protobuf.ByteString
          getForceUpdateUrlBytes() {
        Object ref = forceUpdateUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          forceUpdateUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string force_update_url = 1;</code>
       * @param value The forceUpdateUrl to set.
       * @return This builder for chaining.
       */
      public Builder setForceUpdateUrl(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        forceUpdateUrl_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string force_update_url = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearForceUpdateUrl() {
        forceUpdateUrl_ = getDefaultInstance().getForceUpdateUrl();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string force_update_url = 1;</code>
       * @param value The bytes for forceUpdateUrl to set.
       * @return This builder for chaining.
       */
      public Builder setForceUpdateUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        forceUpdateUrl_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ForceUpdateInfo)
    }

    // @@protoc_insertion_point(class_scope:ForceUpdateInfo)
    private static final org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo();
    }

    public static org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ForceUpdateInfo>
        PARSER = new com.google.protobuf.AbstractParser<ForceUpdateInfo>() {
      @Override
      public ForceUpdateInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ForceUpdateInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ForceUpdateInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public org.nofs.ForceUpdateInfoOuterClass.ForceUpdateInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ForceUpdateInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ForceUpdateInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025ForceUpdateInfo.proto\"+\n\017ForceUpdateIn" +
      "fo\022\030\n\020force_update_url\030\001 \001(\tB\013\n\tsdkserve" +
      "rb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ForceUpdateInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ForceUpdateInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ForceUpdateInfo_descriptor,
        new String[] { "ForceUpdateUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
